services:
  php:
    build:
      context: ./
      dockerfile: prod.Dockerfile
    container_name: php

  web:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    container_name: web-nginx
    environment:
      TARGET_HOST: php
      TARGET_PORT: 9000
      LISTEN_PORT: 80
    ports:
      - "80:80"
    depends_on:
      - php
      - db

  # db:
  #   image: mysql:8.0
  #   restart: unless-stopped
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: "${DB_DATABASE}
  #     MYSQL_USER: "${DB_USERNAME}"
  #     MYSQL_PASSWORD: "${DB_PASSWORD}"
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - ./data/db:/var/lib/mysql

  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  postgres_data:
