services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
    web:
        image: nginx:stable
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
    node:
        image: node:lts
        user: node
        working_dir: /assets
        volumes:
            - ./:/assets
        command: npm run dev

    db:
        image: postgres:17
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
