services:
  php:
    build:
      context: ./
      dockerfile: prod.Dockerfile
    volumes:
      - ./:/var/www/html
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
      && php-fpm"

  node:
    image: node:lts
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "sleep 1 && npm install && npm run dev"
    ports:
      - "5173:5173"
    depends_on:
      - php

  web:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    container_name: web
    environment:
      TARGET_HOST: php
      TARGET_PORT: 9000
      LISTEN_PORT: 80
    ports:
      - "80:80"
    depends_on:
      - php
      - db
    volumes:
      - ./:/var/www/html

  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  postgres_data:
